# Generated by Django 5.2.7 on 2025-10-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_customuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=13),
        ),
    ]
